print(abs.__doc__)
print(int.__doc__)
print(str.__doc__)
print(list.__doc__)
print(dict.__doc__)
print(float.__doc__)
print(tuple.__doc__)
print(complex.__doc__)
print(print.__doc__)
print(range.__doc__)
print(map.__doc__)
print(min.__doc__)
print(max.__doc__)
print(next.__doc__)
print(type.__doc__)
print(round.__doc__)
print(bin.__doc__)
print(oct.__doc__)
print(id.__doc__)
print(pow.__doc__)


