print (abs.__doc__)
print(int.__doc__)
print (input.__doc__)
print(map.__doc__)
print (str.__doc__)
print(float.__doc__)
print (list.__doc__)
print(dict.__doc__)
print (tuple.__doc__)
print(range.__doc__)
print (max.__doc__)
print(min.__doc__)
print (round.__doc__)
print(bin.__doc__)
